[package]
name = "template"
version = "0.1.0"
authors = [""]
edition = "2021"
license = "TODO"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
